name: solana_v1_contrib

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/solana_v1_contrib.yml
      - packages/solana-v1-contrib/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/solana_v1_contrib.yml
      - packages/solana-v1-contrib/**

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn
        working-directory: ./packages/solana-v1-contrib
      - run: yarn build
        working-directory: ./packages/solana-v1-contrib
      - run: yarn test
        working-directory: ./packages/solana-v1-contrib
